import asyncio
from telethon import TelegramClient, events, Button
from telethon.tl.types import ReplyKeyboardMarkup, KeyboardButtonRow, KeyboardButton, KeyboardButtonWebView, ReplyKeyboardHide
from telethon.errors import UserIsBlockedError, FloodWaitError
import aiohttp
import os
import uuid
import sqlite3
import logging
import time

# --- Configuration ---
# !! IMPORTANT: Move these to environment variables or a config file in production !!
API_ID = 18377832                     # Replace with your API ID from https://my.telegram.org
API_HASH = 'ed8556c450c6d0fd68912423325dd09c'          # Replace with your API HASH
BOT_TOKEN = '8122417783:AAEMS-SfdkthJut4CyX7meKY17hCnNZRq6w'   # Replace with your Bot Token

# --- Admin Configuration ---
ADMIN_USER_IDS = [7906104754]  # <-- !!! REPLACE with YOUR Telegram User ID(s) !!!

# --- API & WebApp ---
AI_API_URL = 'https://sitemiker.vercel.app/generate'  # Your AI API endpoint
WEBAPP_HOST = 'https://webview-site.vercel.app/?id='  # WebApp URL for preview

# --- Database ---
DB_NAME = 'bot_database.db'

# --- Localization ---
translations = {
    'fa': {
        "start_welcome": "سلام! 👋 به ربات سازنده وب‌سایت با هوش مصنوعی خوش آمدید.\n\nیک توضیح یا درخواست برای وب‌سایتی که می‌خواهید بسازید، ارسال کنید.",
        "creating_website": "⏳ در حال ساخت وب‌سایت با هوش مصنوعی...",
        "error_creating": "خطا هنگام تولید وب‌سایت: {}",
        "error_invalid_html": "❌ خطا: پاسخ دریافتی از API، یک فایل HTML معتبر نیست.",
        "website_caption": "📄 کد وب‌سایت تولید شده توسط هوش مصنوعی.",
        "live_preview_prompt": "👇 پیش‌نمایش زنده وب‌سایت در مینی‌اپ تلگرام:",
        "view_in_telegram": "👁️ مشاهده در تلگرام",
        "main_menu_button_create": "🚀 شروع ساخت وب‌سایت",
        "main_menu_button_settings": "⚙️ تنظیمات",
        "main_menu_button_contact": "👨‍💻 ارتباط با توسعه‌دهنده",
        "settings_prompt": "زبان مورد نظر خود را انتخاب کنید:",
        "settings_lang_fa": "🇮🇷 فارسی (Persian)",
        "settings_lang_en": "🇬🇧 انگلیسی (English)",
        "settings_lang_set": "✅ زبان به {} تغییر یافت.",
        "contact_info": "برای ارتباط با توسعه‌دهنده به آیدی زیر پیام دهید:\nhttps://t.me/NEXZOtm",
        "banned_message": "🚫 شما توسط مدیر از استفاده از این ربات منع شده‌اید.",
        "admin_panel_title": "پنل مدیریت",
        "admin_stats": "📊 آمار",
        "admin_broadcast": "📢 پیام همگانی",
        "admin_send_user": "✉️ ارسال پیام به کاربر",
        "admin_ban_user": "🚫 بن کردن کاربر",
        "admin_unban_user": "✅ آنبن کردن کاربر",
        "admin_stats_result": "تعداد کل کاربران: {}",
        "admin_broadcast_prompt": "پیام خود را برای ارسال همگانی بنویسید یا به یک پیام (شامل متن یا مدیا) ریپلای کنید.",
        "admin_broadcast_confirm": "پیام همگانی در حال ارسال به {} کاربر...",
        "admin_broadcast_done": "✅ پیام همگانی با موفقیت به {} کاربر ارسال شد. {} کاربر بلاک کرده بودند.",
        "admin_broadcast_failed_user": "⚠️ ارسال پیام همگانی به کاربر {} ناموفق بود: {}",
        "admin_send_user_prompt": "آیدی عددی کاربر و سپس پیام خود را وارد کنید:\n`/send <user_id> <message>`",
        "admin_send_user_confirm": "✅ پیام با موفقیت برای کاربر {} ارسال شد.",
        "admin_send_user_fail": "❌ ارسال پیام به کاربر {} ناموفق بود: {}",
        "admin_ban_prompt": "آیدی عددی کاربری که می‌خواهید بن کنید را وارد کنید:\n`/ban <user_id>`",
        "admin_ban_confirm": "✅ کاربر {} با موفقیت بن شد.",
        "admin_ban_fail": "❌ بن کردن کاربر {} ناموفق بود. شاید کاربر وجود نداشته باشد؟",
        "admin_unban_prompt": "آیدی عددی کاربری که می‌خواهید آنبن کنید را وارد کنید:\n`/unban <user_id>`",
        "admin_unban_confirm": "✅ کاربر {} با موفقیت آنبن شد.",
        "admin_unban_fail": "❌ آنبن کردن کاربر {} ناموفق بود.",
        "admin_invalid_command": "❌ دستور نامعتبر است.",
        "error_generic": "⚠️ خطایی رخ داد. لطفاً دوباره تلاش کنید یا با توسعه‌دهنده تماس بگیرید.",
        "processing_request": "⏳ در حال پردازش درخواست شما...",
        "prompt_placeholder": "مثال: یک صفحه لندینگ ساده برای یک اپلیکیشن موبایل با تم آبی...",
        "send_prompt_instruction": "👇 لطفا دستور ساخت وبسایت را بنویسید:",

    },
    'en': {
        "start_welcome": "Hello! 👋 Welcome to the AI Website Builder Bot.\n\nSend a description or request for the website you want to create.",
        "creating_website": "⏳ Building website with AI...",
        "error_creating": "Error during website generation: {}",
        "error_invalid_html": "❌ Error: The response received from the API is not valid HTML.",
        "website_caption": "📄 Website code generated by AI.",
        "live_preview_prompt": "👇 Live preview of the website in the Telegram Mini App below:",
        "view_in_telegram": "👁️ View in Telegram",
        "main_menu_button_create": "🚀 Start Building Website",
        "main_menu_button_settings": "⚙️ Settings",
        "main_menu_button_contact": "👨‍💻 Contact Developer",
        "settings_prompt": "Choose your preferred language:",
        "settings_lang_fa": "🇮🇷 فارسی (Persian)",
        "settings_lang_en": "🇬🇧 English",
        "settings_lang_set": "✅ Language changed to {}.",
        "contact_info": "To contact the developer, send a message to:\nhttps://t.me/NEXZOtm",
        "banned_message": "🚫 You have been banned from using this bot by the administrator.",
        "admin_panel_title": "Admin Panel",
        "admin_stats": "📊 Statistics",
        "admin_broadcast": "📢 Broadcast Message",
        "admin_send_user": "✉️ Send Message to User",
        "admin_ban_user": "🚫 Ban User",
        "admin_unban_user": "✅ Unban User",
        "admin_stats_result": "Total users: {}",
        "admin_broadcast_prompt": "Write your message for broadcast or reply to a message (containing text or media).",
        "admin_broadcast_confirm": "Broadcasting message to {} users...",
        "admin_broadcast_done": "✅ Broadcast successfully sent to {} users. {} users had blocked the bot.",
        "admin_broadcast_failed_user": "⚠️ Failed to send broadcast to user {}: {}",
        "admin_send_user_prompt": "Enter the user's numeric ID and your message:\n`/send <user_id> <message>`",
        "admin_send_user_confirm": "✅ Message successfully sent to user {}.",
        "admin_send_user_fail": "❌ Failed to send message to user {}: {}",
        "admin_ban_prompt": "Enter the numeric ID of the user you want to ban:\n`/ban <user_id>`",
        "admin_ban_confirm": "✅ User {} successfully banned.",
        "admin_ban_fail": "❌ Failed to ban user {}. Maybe the user doesn't exist?",
        "admin_unban_prompt": "Enter the numeric ID of the user you want to unban:\n`/unban <user_id>`",
        "admin_unban_confirm": "✅ User {} successfully unbanned.",
        "admin_unban_fail": "❌ Failed to unban user {}.",
        "admin_invalid_command": "❌ Invalid command.",
        "error_generic": "⚠️ An error occurred. Please try again or contact the developer.",
        "processing_request": "⏳ Processing your request...",
        "prompt_placeholder": "Example: A simple landing page for a mobile app with a blue theme...",
         "send_prompt_instruction": "👇 Please write the prompt for the website:",
    }
}

# --- Logging Setup ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# --- Database Functions ---
def db_connect():
    """Creates a database connection."""
    return sqlite3.connect(DB_NAME)

def db_setup():
    """Sets up the database tables if they don't exist."""
    conn = db_connect()
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS users (
            user_id INTEGER PRIMARY KEY,
            username TEXT,
            first_name TEXT,
            last_name TEXT,
            language TEXT DEFAULT 'fa',
            is_banned INTEGER DEFAULT 0,
            join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    # Add more tables if needed (e.g., admins)
    conn.commit()
    conn.close()
    logger.info("Database setup complete.")

def get_user_lang(user_id):
    """Gets the user's preferred language."""
    conn = db_connect()
    cursor = conn.cursor()
    cursor.execute('SELECT language FROM users WHERE user_id = ?', (user_id,))
    result = cursor.fetchone()
    conn.close()
    return result[0] if result else 'fa'  # Default to Persian

def update_user_lang(user_id, lang_code):
    """Updates the user's language preference."""
    conn = db_connect()
    cursor = conn.cursor()
    cursor.execute('UPDATE users SET language = ? WHERE user_id = ?', (lang_code, user_id))
    conn.commit()
    conn.close()

def add_or_update_user(user_id, username, first_name, last_name):
    """Adds a new user or updates existing user's info, keeping language and banned status."""
    conn = db_connect()
    cursor = conn.cursor()
    cursor.execute('''
        INSERT INTO users (user_id, username, first_name, last_name)
        VALUES (?, ?, ?, ?)
        ON CONFLICT(user_id) DO UPDATE SET
            username = excluded.username,
            first_name = excluded.first_name,
            last_name = excluded.last_name
    ''', (user_id, username, first_name, last_name))
    conn.commit()
    conn.close()

def is_user_banned(user_id):
    """Checks if a user is banned."""
    conn = db_connect()
    cursor = conn.cursor()
    cursor.execute('SELECT is_banned FROM users WHERE user_id = ?', (user_id,))
    result = cursor.fetchone()
    conn.close()
    return result and result[0] == 1

def set_user_banned_status(user_id, banned_status):
    """Sets the banned status for a user."""
    conn = db_connect()
    cursor = conn.cursor()
    # Ensure user exists before trying to update
    cursor.execute('INSERT OR IGNORE INTO users (user_id) VALUES (?)', (user_id,))
    cursor.execute('UPDATE users SET is_banned = ? WHERE user_id = ?', (1 if banned_status else 0, user_id))
    updated_rows = conn.total_changes # Check if the update actually happened
    conn.commit()
    conn.close()
    # Check if the user existed or was inserted, and then updated
    cursor = db_connect().cursor()
    cursor.execute('SELECT EXISTS(SELECT 1 FROM users WHERE user_id=?)',(user_id,))
    user_exists = cursor.fetchone()[0]
    db_connect().close()
    return user_exists > 0 # Return True if user exists (and thus update likely worked or user was inserted)


def get_all_user_ids(include_banned=False):
    """Gets all user IDs from the database."""
    conn = db_connect()
    cursor = conn.cursor()
    query = 'SELECT user_id FROM users'
    if not include_banned:
        query += ' WHERE is_banned = 0'
    cursor.execute(query)
    results = [row[0] for row in cursor.fetchall()]
    conn.close()
    return results

def count_users():
    """Counts the total number of users."""
    conn = db_connect()
    cursor = conn.cursor()
    cursor.execute('SELECT COUNT(*) FROM users')
    result = cursor.fetchone()
    conn.close()
    return result[0] if result else 0


# --- Helper Functions ---
def get_string(user_id, key, lang_code=None):
    """Gets the translated string for the user's language."""
    if lang_code is None:
        lang_code = get_user_lang(user_id)
    return translations.get(lang_code, translations['fa']).get(key, f"[{key}]") # Default to fa if lang not found

async def is_admin(user_id):
    """Checks if a user ID belongs to an admin."""
    # In this version, we check against the hardcoded list.
    # You could enhance this to check a 'is_admin' column in the database.
    return user_id in ADMIN_USER_IDS

# --- Initialize Database ---
db_setup()

# --- Initialize Telegram Client ---
client = TelegramClient('bot_session', API_ID, API_HASH)

# --- Main Menu Keyboard ---
async def get_main_menu(user_id):
    lang = get_user_lang(user_id)
    return ReplyKeyboardMarkup(
        [
            KeyboardButtonRow(
                [KeyboardButton(text=get_string(user_id, "main_menu_button_create", lang))]
            ),
            KeyboardButtonRow(
                [
                    KeyboardButton(text=get_string(user_id, "main_menu_button_settings", lang)),
                    KeyboardButton(text=get_string(user_id, "main_menu_button_contact", lang)),
                ]
            ),
        ],
        resize=True
    )

# --- Bot Event Handlers ---

@client.on(events.NewMessage(pattern='/start'))
async def start_handler(event):
    """Handles the /start command."""
    sender = await event.get_sender()
    user_id = sender.id
    username = sender.username
    first_name = sender.first_name
    last_name = sender.last_name

    add_or_update_user(user_id, username, first_name, last_name)

    if await is_user_banned(user_id):
        await event.reply(get_string(user_id, "banned_message"))
        return

    logger.info(f"User {user_id} ({username}) started the bot.")
    menu = await get_main_menu(user_id)
    await event.respond(get_string(user_id, "start_welcome"), buttons=menu)
    # Raise exception to stop processing other handlers if needed
    # raise events.StopPropagation

@client.on(events.NewMessage)
async def main_menu_handler(event):
    """Handles main menu button presses."""
    sender = await event.get_sender()
    user_id = sender.id
    text = event.raw_text

    if await is_user_banned(user_id):
        # Don't reply to banned users unless it's an unban command from admin
        command_part = text.split(" ")[0]
        if not (await is_admin(user_id) and command_part in ['/unban']):
             logger.warning(f"Ignoring message from banned user {user_id}: {text}")
             # Optionally send the banned message again, or just ignore
             # await event.reply(get_string(user_id, "banned_message"))
             raise events.StopPropagation # Stop processing further
        # Allow admins to potentially unban

    # Check if the message text matches any main menu button text for the user's language
    lang = get_user_lang(user_id)
    if text == get_string(user_id, "main_menu_button_create", lang):
        await event.reply(get_string(user_id, "send_prompt_instruction", lang), buttons=ReplyKeyboardHide()) # Hide menu when asking for prompt
    elif text == get_string(user_id, "main_menu_button_settings", lang):
        await settings_handler(event)
    elif text == get_string(user_id, "main_menu_button_contact", lang):
        await event.reply(get_string(user_id, "contact_info", lang), buttons=await get_main_menu(user_id)) # Keep menu open
    # else:
        # Let it fall through to the prompt handler or admin commands
        # pass


async def settings_handler(event):
    """Handles the 'Settings' button press or /settings command."""
    user_id = event.sender_id
    lang = get_user_lang(user_id)

    buttons = [
        [Button.inline(get_string(user_id, "settings_lang_fa", lang), data='setlang_fa')],
        [Button.inline(get_string(user_id, "settings_lang_en", lang), data='setlang_en')]
    ]
    await event.reply(get_string(user_id, "settings_prompt", lang), buttons=buttons)

@client.on(events.CallbackQuery(pattern=b'setlang_(fa|en)'))
async def set_language_callback(event):
    """Handles language selection callback."""
    user_id = event.sender_id
    lang_code = event.data.decode('utf-8').split('_')[1]

    update_user_lang(user_id, lang_code)
    logger.info(f"User {user_id} changed language to {lang_code}")

    # Use the newly set language for the confirmation message
    confirmation_text = get_string(user_id, "settings_lang_set", lang_code).format(
        get_string(user_id, f"settings_lang_{lang_code}", lang_code) # Get the language name in its own language
    )

    try:
        # Edit the original message to show confirmation
        await event.edit(confirmation_text)
        # Send the main menu again with updated language
        await event.respond(get_string(user_id,"start_welcome", lang_code), buttons=await get_main_menu(user_id))
    except Exception as e:
        logger.error(f"Error updating language message for {user_id}: {e}")
        # Fallback: Answer the callback query simply
        await event.answer(get_string(user_id, "settings_lang_set", lang_code).format(lang_code.upper()))


@client.on(events.NewMessage(pattern='^(?!/).+'))  # Catches non-command messages
async def handle_prompt(event):
    """Handles user prompts for website generation."""
    sender = await event.get_sender()
    user_id = sender.id
    user_prompt = event.raw_text.strip()

    # Ignore empty messages or potential button presses that slipped through
    if not user_prompt:
        return

    # Check if the text matches a menu button again (in case menu handler didn't catch it)
    lang = get_user_lang(user_id)
    if user_prompt in [get_string(user_id, btn, lang) for btn in ["main_menu_button_create", "main_menu_button_settings", "main_menu_button_contact"]]:
        # It's likely a button press, let the main_menu_handler deal with it or ignore
        logger.debug(f"Ignoring likely button press from {user_id}: {user_prompt}")
        return

    # --- User Checks ---
    add_or_update_user(user_id, sender.username, sender.first_name, sender.last_name) # Ensure user exists

    if await is_user_banned(user_id):
        await event.reply(get_string(user_id, "banned_message"))
        return

    logger.info(f"Prompt received from {user_id} ({sender.username}): {user_prompt}")
    msg = await event.reply(get_string(user_id, "creating_website"))

    try:
        # --- Call AI API ---
        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=120)) as session: # Increased timeout slightly
             # Add headers if your API requires them (e.g., auth tokens)
             headers = {"Content-Type": "application/json"} # Example header
             async with session.post(AI_API_URL, json={"prompt": user_prompt}, headers=headers) as resp:
                if resp.status == 200:
                    html_code = await resp.text()
                else:
                    error_text = await resp.text()
                    logger.error(f"API Error for user {user_id}. Status: {resp.status}, Response: {error_text[:500]}") # Log part of the error
                    await msg.edit(get_string(user_id, "error_creating").format(f"API Status {resp.status}"))
                    return


        # Basic HTML validation (check for <!doctype html>)
        if not html_code or not html_code.strip().lower().startswith("<!doctype html"):
            logger.warning(f"Invalid HTML received for user {user_id}. Response: {html_code[:500]}") # Log part of the invalid response
            await msg.edit(get_string(user_id, "error_invalid_html"))
            return

        # --- Save HTML File ---
        unique_id = str(uuid.uuid4())
        # Store files in a dedicated directory (ensure it exists)
        output_dir = "generated_websites"
        os.makedirs(output_dir, exist_ok=True)
        file_name = f"website_{unique_id[:8]}.html"
        file_path = os.path.join(output_dir, file_name)

        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(html_code)
        logger.info(f"HTML file saved for user {user_id}: {file_path}")

        # --- Send File to User ---
        try:
            await client.send_file(
                event.chat_id,
                file_path,
                caption=get_string(user_id, "website_caption"),
                reply_to=event.id
            )
        except Exception as e:
            logger.error(f"Failed to send file {file_path} to {user_id}: {e}")
            await msg.edit(get_string(user_id, "error_generic")) # Inform user about generic error
            # Don't delete the file yet if sending failed, maybe retry later or log for admin
            return # Stop further processing for this request


        # --- Send WebApp Button ---
        # Construct the web app URL. IMPORTANT: Ensure your web app at WEBAPP_HOST
        # knows how to handle this ID to display the correct preview.
        # This usually means the web app needs access to the generated content,
        # possibly by fetching it from a server endpoint using the unique_id.
        # The current structure implies the web app fetches content independently.
        webapp_url = f"{WEBAPP_HOST}{unique_id}" # Using the full UUID might be safer

        await client.send_message(
            event.chat_id,
            get_string(user_id, "live_preview_prompt"),
            buttons=[[
                # Use KeyboardButtonWebView for inline web apps
                 KeyboardButton(
                    text=get_string(user_id, "view_in_telegram"),
                    url=webapp_url # For simple link button
                 )
                 # Or for integrated webview:
                 # Button.web_app( # requires telethon >= 1.25 approx
                 #    text=get_string(user_id, "view_in_telegram"),
                 #    url=webapp_url
                 # )
                 # Or using the older way if Button.web_app is not available
                 # Button.url( # This just opens the browser
                 #      text=get_string(user_id, "view_in_telegram"),
                 #      url=webapp_url
                 # )
                 # Let's try the KeyboardButtonWebView approach which is standard for bots
                 # This needs to be part of a ReplyKeyboardMarkup or InlineKeyboardMarkup
                 # Sending it standalone is tricky. Let's use an inline button:

            ],[
                 Button.web_app(get_string(user_id, "view_in_telegram"), webapp_url)
            ]],
            reply_to=event.id
        )

        # --- Cleanup ---
        try:
            os.remove(file_path)
            logger.info(f"Cleaned up file: {file_path}")
        except OSError as e:
            logger.error(f"Error removing file {file_path}: {e}")

        # Edit the initial "Creating..." message to indicate completion (optional)
        await msg.delete() # Or edit it to something like "Website generated!"

    except aiohttp.ClientError as e:
        logger.error(f"HTTP Client Error for user {user_id}: {e}")
        await msg.edit(get_string(user_id, "error_creating").format("Connection Error"))
    except asyncio.TimeoutError:
        logger.error(f"Timeout Error for user {user_id} calling API.")
        await msg.edit(get_string(user_id, "error_creating").format("Request Timeout"))
    except Exception as e:
        logger.exception(f"Unhandled error processing prompt for user {user_id}: {e}") # Log full traceback
        await msg.edit(get_string(user_id, "error_generic"))

# --- Admin Commands ---

@client.on(events.NewMessage(pattern='/admin', func=lambda e: e.sender_id in ADMIN_USER_IDS))
async def admin_panel_handler(event):
    """Displays the admin panel."""
    user_id = event.sender_id
    buttons = [
        [Button.inline(get_string(user_id, "admin_stats"), data='admin_stats')],
        [Button.inline(get_string(user_id, "admin_broadcast"), data='admin_broadcast_prompt')],
        # [Button.inline(get_string(user_id, "admin_send_user"), data='admin_send_user_prompt')], # Less intuitive with inline
        [Button.inline(get_string(user_id, "admin_ban_user"), data='admin_ban_prompt')],
        [Button.inline(get_string(user_id, "admin_unban_user"), data='admin_unban_prompt')],
    ]
    await event.reply(get_string(user_id, "admin_panel_title"), buttons=buttons)

@client.on(events.CallbackQuery(pattern=b'admin_stats', func=lambda e: e.sender_id in ADMIN_USER_IDS))
async def admin_stats_callback(event):
    """Handles the admin stats request."""
    user_id = event.sender_id
    total = count_users()
    await event.answer(get_string(user_id, "admin_stats_result").format(total), alert=True)


# --- Admin Broadcast ---
admin_waiting_for_broadcast = set()

@client.on(events.CallbackQuery(pattern=b'admin_broadcast_prompt', func=lambda e: e.sender_id in ADMIN_USER_IDS))
async def admin_broadcast_prompt_callback(event):
    """Prompts admin to send the broadcast message."""
    user_id = event.sender_id
    admin_waiting_for_broadcast.add(user_id)
    await event.edit(get_string(user_id, "admin_broadcast_prompt")) # Edit the panel message
    await event.answer() # Acknowledge callback


@client.on(events.NewMessage(func=lambda e: e.sender_id in admin_waiting_for_broadcast))
async def admin_broadcast_receive_handler(event):
    """Receives the message/media admin wants to broadcast."""
    admin_id = event.sender_id

    if admin_id not in admin_waiting_for_broadcast:
         return # Should not happen based on func filter, but safety check

    admin_waiting_for_broadcast.remove(admin_id) # Process only once

    message_to_broadcast = event.message # This includes text, media, entities, etc.

    user_ids = get_all_user_ids(include_banned=False)
    if not user_ids:
        await event.reply("No users found to broadcast to.")
        return

    count = len(user_ids)
    await event.reply(get_string(admin_id, "admin_broadcast_confirm").format(count))
    logger.info(f"Admin {admin_id} starting broadcast to {count} users.")

    success_count = 0
    blocked_count = 0
    start_time = time.time()

    for user_id in user_ids:
        if user_id == admin_id: # Don't broadcast to self (optional)
             continue
        try:
            # Forwarding is often easier and preserves formatting/media correctly
            # await client.forward_messages(user_id, message_to_broadcast)
            # Or send a copy (if forwarding is not desired or causes issues)
            await client.send_message(user_id, message_to_broadcast)
            success_count += 1
            logger.debug(f"Broadcast sent to {user_id}")
        except UserIsBlockedError:
            logger.warning(f"User {user_id} blocked the bot. Skipping broadcast.")
            blocked_count += 1
        except FloodWaitError as e:
            logger.warning(f"Flood wait of {e.seconds} seconds encountered during broadcast.")
            await asyncio.sleep(e.seconds + 1) # Wait extra second
            # Retry sending to the same user after wait
            try:
                 await client.send_message(user_id, message_to_broadcast)
                 success_count += 1
                 logger.debug(f"Broadcast sent to {user_id} after flood wait.")
            except Exception as retry_e:
                 logger.error(get_string(admin_id, "admin_broadcast_failed_user").format(user_id, retry_e))
        except Exception as e:
            logger.error(get_string(admin_id, "admin_broadcast_failed_user").format(user_id, e))

        # Sleep briefly between messages to avoid hitting limits too quickly
        await asyncio.sleep(0.1) # Adjust sleep time as needed (0.05 to 0.2 is common)

    end_time = time.time()
    duration = end_time - start_time
    logger.info(f"Broadcast finished in {duration:.2f} seconds.")
    await event.reply(get_string(admin_id, "admin_broadcast_done").format(success_count, blocked_count))


# --- Admin Ban/Unban --- (Using commands for simplicity)

@client.on(events.NewMessage(pattern=r'/ban (\d+)', func=lambda e: e.sender_id in ADMIN_USER_IDS))
async def admin_ban_handler(event):
    """Handles banning a user."""
    admin_id = event.sender_id
    try:
        user_to_ban = int(event.pattern_match.group(1))
        if user_to_ban in ADMIN_USER_IDS:
            await event.reply("Cannot ban an admin.")
            return

        if set_user_banned_status(user_to_ban, True):
            logger.info(f"Admin {admin_id} banned user {user_to_ban}")
            await event.reply(get_string(admin_id, "admin_ban_confirm").format(user_to_ban))
        else:
            await event.reply(get_string(admin_id, "admin_ban_fail").format(user_to_ban))
    except Exception as e:
        logger.error(f"Error in /ban command by {admin_id}: {e}")
        await event.reply(get_string(admin_id, "admin_invalid_command"))


@client.on(events.NewMessage(pattern=r'/unban (\d+)', func=lambda e: e.sender_id in ADMIN_USER_IDS))
async def admin_unban_handler(event):
    """Handles unbanning a user."""
    admin_id = event.sender_id
    try:
        user_to_unban = int(event.pattern_match.group(1))
        if set_user_banned_status(user_to_unban, False):
             logger.info(f"Admin {admin_id} unbanned user {user_to_unban}")
             await event.reply(get_string(admin_id, "admin_unban_confirm").format(user_to_unban))
        else:
             await event.reply(get_string(admin_id, "admin_unban_fail").format(user_to_unban))

    except Exception as e:
        logger.error(f"Error in /unban command by {admin_id}: {e}")
        await event.reply(get_string(admin_id, "admin_invalid_command"))


# --- Admin Send Message to User ---

@client.on(events.NewMessage(pattern=r'/send (\d+) (.+)', func=lambda e: e.sender_id in ADMIN_USER_IDS))
async def admin_send_user_handler(event):
     """Handles sending a message to a specific user."""
     admin_id = event.sender_id
     try:
        target_user_id = int(event.pattern_match.group(1))
        message_text = event.pattern_match.group(2).strip()

        if not message_text:
             await event.reply("Please provide a message to send.")
             return

        # Simple text sending for now. Can be enhanced to forward replies.
        await client.send_message(target_user_id, f"Message from admin:\n\n{message_text}")
        logger.info(f"Admin {admin_id} sent message to {target_user_id}")
        await event.reply(get_string(admin_id, "admin_send_user_confirm").format(target_user_id))

     except UserIsBlockedError:
        logger.warning(f"Admin {admin_id} failed to send message to {target_user_id}: User blocked bot.")
        await event.reply(get_string(admin_id, "admin_send_user_fail").format(target_user_id, "User blocked the bot"))
     except Exception as e:
        logger.error(f"Error in /send command by {admin_id}: {e}")
        await event.reply(get_string(admin_id, "admin_send_user_fail").format(target_user_id, str(e)))

# --- Generic Error Handler (Optional but Recommended) ---
# This could catch errors not handled elsewhere, though specific handlers are better.
# @client.on(events.ChatAction) # Example: Handle users leaving/joining if needed
# async def handler(event):
#     pass


# --- Start the Bot ---
async def main():
    # Start the client
    # Use BOT_TOKEN if it's a bot account, otherwise login interactively or with phone/password
    await client.start(bot_token=BOT_TOKEN)
    logger.info("Bot started successfully!")
    me = await client.get_me()
    logger.info(f"Running as: {me.username} (ID: {me.id})")
    logger.info("Admin IDs: %s", ADMIN_USER_IDS)
    logger.info("Bot is running...")
    await client.run_until_disconnected()

if __name__ == '__main__':
    # Ensure the event loop runs the main function
    # Older python versions might need: loop = asyncio.get_event_loop(); loop.run_until_complete(main())
    asyncio.run(main())
